### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by wade-liwei** [decentraland/explorer-website#122]
npm run start

backend:
Error: ENOENT: no such file or directory, stat '/Users/c/go/src/github.com/decentraland/kernel/static/index.js'
Error: ENOENT: no such file or directory, stat '/Users/c/go/src/github.com/decentraland/kernel/static/index.js'

frontend:

rollbar.min.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of RefFindNode which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node

**Comment by juanigallo** [comment]
Hi @wade-liwei that issue happens when you don't have the `kernel` server running. To know how to do it you can check [this link](https://github.com/decentraland/kernel#readme)
