### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by WittyAngel** [decentraland/explorer-website#190]
Hi,
I launched explorer-website project with `npm run start` command.
It shows startup page like (https://play.decentraland.org), but if I clicked guest mode or wallet mode, it is not working.
I got below error

```
Sending ./node_modules/@dcl/unity-renderer/index.js
Error: ENOENT: no such file or directory, stat '/home/ubuntu/decentraland/explorer-website/node_modules/@dcl/unity-renderer/unity.framework.js.br'
Sending ./node_modules/@dcl/unity-renderer/index.js.map
Error: ENOENT: no such file or directory, stat '/home/ubuntu/decentraland/explorer-website/node_modules/@dcl/unity-renderer/unity.data.br'
```

please help to launch this explorer-website on my ubuntu system
Thanks

**Comment by Icekettle** [comment]
Do it like this:

https://github.com/web3/web3.js#trouble-shooting-and-known-issues
