### ISSUE TITLE
New sign in flow

### ISSUE THREAD

**Issue by 2fd** [decentraland/explorer-website#231]
Design: https://www.figma.com/file/PPTSbgXl8LA3LB0gHBNqns/Wallet-onboarding?node-id=586%3A1251
Definition: https://www.notion.so/decentraland/aac60f31414946cda176f3819508b605?v=a97f33d0996f4020b8bc19ea02780da2&p=fdbc80c57dec41dbb424cd7e0af5d7df

-------

<img width="753" alt="Screen Shot 2022-06-16 at 20 32 47" src="https://user-images.githubusercontent.com/208789/174141736-db03ac68-ade1-42db-a205-4c2de6f6ef01.png">

- [x] A/B testing:
   - only on web
   - use [ADR-73](https://github.com/decentraland/adr/blob/main/docs/ADR-73-ab-testing.md) standard
   - use  [`toFeatureList`](https://github.com/decentraland/feature-flags) to reports  feature list
- [x] `PLAY AS A GUEST` should log in the user as guest (same as the current `Play as Guest`)
- [x] `SIGN IN` and `CREATE AN ACCOUNT` should both send the user to the next step
- [x] action should trigger on click over card, not just on the button

-------

<img width="496" alt="Screen Shot 2022-06-16 at 20 32 41" src="https://user-images.githubusercontent.com/208789/174141798-438dbbde-de68-44c8-a070-60f6ff359b6a.png">

- [x] keep the current behaviour (adding wallet link)
- [x] `I don't ... wallet` should take user to step 3

-------

<img width="537" alt="Screen Shot 2022-06-16 at 20 32 34" src="https://user-images.githubusercontent.com/208789/174141836-0515a64a-9cef-4800-b134-5f643293f39e.png">

- [x] keep the current behaviour (adding wallet link)

**Comment by braianj** [comment]
Design update: [here](https://www.figma.com/file/PPTSbgXl8LA3LB0gHBNqns/Wallet-onboarding?node-id=876%3A1211)
