### ISSUE TITLE
MessageBus only sends to myself

### ISSUE THREAD

**Issue by aminekha** [decentraland/explorer-website#312]
MessageBus only send to myself and not to other players. I even tried the [code demo](https://docs.decentraland.org/creator/development-guide/remote-scene-considerations/#full-example) on the Decenraland website and it's not working.

Is there something wrong with the Decentraland servers?

**Comment by kuruk-mm** [comment]
I tried, and I was not able to reproduce it.

Have you tested in the preview mode (when you open the scene with `dcl start`)?

The problem is still there? Can you provide more information about it?

Thanks!

**Comment by aminekha** [comment]
Yes, I tested and it doesn't work.
Is the demo code working for you?

Here's my code:

> channelBus.emit("roomOneNext", {});
>

channelBus.on("roomOneNext", () => {

   one = nextImage(roomOneImages, one, 2.5, 4, 1);

})


When I click on the "Next" button in my scene, the image change for me but
not for players in the same room.

Here's a link to my scene: play.decentraland.org/?position=-21,148

**Comment by pravusjif** [comment]
The issue could be reproduced, it happens only on deployed lands, it's being debugged to find a solution

**Comment by pravusjif** [comment]
@aminekha the bug has been fixed, thanks for reporting.
